import Head from "next/head";
import Image from "next/image";
import MedicationChecklist from "../components/medicationChecklist";
import DisplayName from "../components/displayName";
import CurrentStreak from "../components/currentStreak";
import RewardBox from "../components/rewardBox";
import MedicineBox from "../components/medicineBox";
import AlertBox from "../components/alertBox";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DisplayName name={"Oli"}></DisplayName>
        <CurrentStreak currentStreak={7}></CurrentStreak>
        <AlertBox></AlertBox>
        <MedicationChecklist></MedicationChecklist>
        <RewardBox></RewardBox>
        <MedicineBox
          medicineObj={{ drug: "Ramipril", remaining: 7, total: 28 }}
        ></MedicineBox>
      </main>
    </div>
  );
}
